apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-api-deployment
  labels:
    app: aspnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-api
  template:
    metadata:
      labels:
        app: aspnet-api
    spec:
      containers:
        - name: aspnet-api-container
          image: my-aspnet-api:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-api-service
spec:
  type: NodePort
  selector:
    app: aspnet-api
  ports:
    - port: 80         # Service port inside cluster
      targetPort: 80   # Container port
      nodePort: 30080  # Port exposed on your machine